spring:
  application:
    name: Galio
  jpa:
    hibernate:
      ddl-auto: update
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**
  session:
    jdbc:
      initialize-schema: always
  datasource:
    hikari:
      connection-init-sql: "SET collation_connection = 'utf8mb4_unicode_ci'"
logging:
  level:
    root: info
    de.kaleidox: debug
    org.comroid: debug
    com.ampznetwork: debug
